GET http://localhost:3001/todos
###
POST http://localhost:3001/todos/new
Content-Type: application/json

{
    "text": "Ball"
}

### 

DELETE http://localhost:3001/todos/delete/65228c60d448306a184decdb

###
PUT http://localhost:3001/todos/complete/65228bc9d448306a184decd5